services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: battle_nest_dev
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nest_network

  db:
    image: postgres:16-alpine
    container_name: postgres_dev
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - nest_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    networks:
      - nest_network

volumes:
  postgres_dev_data:
  pgadmin_dev_data:

networks:
  nest_network:
    driver: bridge